# Generated by Django 4.0.2 on 2022-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storesetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=255)),
                ('s_email', models.CharField(max_length=255)),
                ('s_phone', models.CharField(max_length=255)),
                ('s_logo', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
    ]
